language: node_js
node_js:
    - '14'
sudo: required
dist: xenial
addons:
    apt:
        packages:
            - libgconf-2-4
    chrome: stable
    sonarcloud:
        organization: 'rickvandermey'
        token: $SONAR_TOKEN
cache:
    directories:
        - $HOME/.npm
        - $HOME/.cache
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
install:
    - npm install codecov -g
    - npm ci
script:
    - npm run lint
    - npm run test:ci
    - node node_modules/protractor/bin/webdriver-manager update
    - npm run test:e2e
    - npm run prerender:build
    - sonar-scanner
after_success:
    - codecov
