language: node_js
node_js:
    - '10'
sudo: required
dist: trusty
addons:
    chrome: stable
cache:
    directories:
        - $HOME/.npm
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install codecov -g
    - npm ci
script:
    # run build script specified in package.json
    - npm run lint
    - npm run prerender:build
    - npm run test:unit-headless
    - npm run test:e2e
after_success:
    - codecov
